In [144]:
import cv2
import tensorflow as tf
CATEGORIES = ["CLUSTER","GALAXY", "LENSE", "NEBULA"]
def prepare(file):
    IMG_SIZE = 100 # MUST BE THE SAME AS THE MODEL
    img_array = cv2.imread(file, cv2.IMREAD_GRAYSCALE)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 1)

model = tf.keras.models.load_model("ASTRODETECTOR.model")

pred = model.predict([prepare("nebula.jpg")])
predicted_class = tf.argmax(pred, axis=1).numpy()[0]
predicted_label = CATEGORIES[predicted_class]
print(pred)
print("Predicted class:", predicted_class)
print("TYPE:", predicted_label)

1/1 [==============================] - 0s 115ms/step
[[0. 0. 0. 1.]]
Clase predicha: 3
Etiqueta correspondiente: NEBULA


In [151]:
pred = model.predict([prepare("nebula2.jpg")])
predicted_class = tf.argmax(pred, axis=1).numpy()[0]
predicted_label = CATEGORIES[predicted_class]
print(pred)

print("Predicted class:", predicted_class)
print("TYPE:", predicted_label)

1/1 [==============================] - 0s 37ms/step
[[0. 0. 0. 1.]]
Predicted class: 3
TYPE: NEBULA


In [152]:
pred = model.predict([prepare("cluster.jpg")])
predicted_class = tf.argmax(pred, axis=1).numpy()[0]
predicted_label = CATEGORIES[predicted_class]
print(pred)
print("Predicted class:", predicted_class)
print("TYPE:", predicted_label)

1/1 [==============================] - 0s 23ms/step
[[1. 0. 0. 0.]]
Predicted class: 0
TYPE: CLUSTER


In [161]:
pred = model.predict([prepare("lense4.jpg")])
predicted_class = tf.argmax(pred, axis=1).numpy()[0]
predicted_label = CATEGORIES[predicted_class]
print(pred)

print("Predicted class:", predicted_class)
print("TYPE:", predicted_label)

1/1 [==============================] - 0s 21ms/step
[[0. 0. 1. 0.]]
Predicted class: 2
TYPE: LENSE


In [157]:
pred = model.predict([prepare("lense1.jpg")])
predicted_class = tf.argmax(pred, axis=1).numpy()[0]
predicted_label = CATEGORIES[predicted_class]
print(pred)
print("Predicted class:", predicted_class)
print("TYPE:", predicted_label)

1/1 [==============================] - 0s 18ms/step
Predicted class: 2
TYPE: LENSE


In [163]:
pred = model.predict([prepare("galaxy2.jpg")])
predicted_class = tf.argmax(pred, axis=1).numpy()[0]
predicted_label = CATEGORIES[predicted_class]
print(pred)
print("Predicted class:", predicted_class)
print("TYPE:", predicted_label)

1/1 [==============================] - 0s 19ms/step
[[0. 0. 1. 0.]]
Predicted class: 2
TYPE: LENSE
